// src/features/counterslice.js
// Translations & shared utilities for Smart Agriculture System

export const translations = {
  en: {
    // App
    appName: 'AgriSmart', appSub: 'Intelligence for Farmers',
    // Nav
    dashboard: 'Dashboard', crop: 'Crop Recommendation', disease: 'Disease Detection',
    ai: 'AI Advisory', weather: 'Weather', profile: 'My Profile',
    email: 'Email Alerts', admin: 'Manage Farmers', signout: 'Sign Out',
    mainSection: 'Main', adminSection: 'Admin',
    // Theme/Lang
    darkMode: 'Dark', lightMode: 'Light',
    // Auth
    signin: 'Sign In', signup: 'Create Account',
    username: 'Username', password: 'Password', emailLbl: 'Email', role: 'Role',
    farmerRole: 'Farmer', adminRole: 'Admin',
    noAccount: "Don't have an account?", haveAccount: 'Already have an account?',
    register: 'Register', signingIn: 'Signing in…', creating: 'Creating…',
    fillFields: 'Fill in all fields', invalidCreds: 'Invalid credentials',
    regSuccess: 'Account created! Please sign in.',
    // Dashboard
    goodDay: 'Good day', dashSub: 'Your smart agriculture assistant is ready.',
    quickTips: 'Quick Tips', howWorks: 'How It Works',
    tip1: 'Upload clear, well-lit leaf photos for best disease detection.',
    tip2: 'Enter accurate NPK values from your soil test report.',
    tip3: 'Check weather before applying fertilizers — avoid rainy days.',
    s1t: 'Input soil data', s1d: 'Provide NPK, humidity, temperature',
    s2t: 'ML Prediction',  s2d: 'Our model recommends the best crop',
    s3t: 'AI Explanation', s3d: 'Get actionable fertilizer & pesticide advice',
    clickOpen: 'Click to open →',
    // Crop
    soilParams: 'Soil Parameters', soilSub: 'Enter your soil & environment data',
    temperature: 'Temperature (°C)', humidity: 'Humidity (%)', rainfall: 'Rainfall (mm)',
    ph: 'Soil pH (0–14)', nitrogen: 'Nitrogen (N)', phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)', location: 'Location (optional)',
    getCrop: 'Get Crop Recommendation', analyzing: 'Analyzing…',
    noPred: 'No prediction yet', fillSoil: 'Fill soil parameters and click Recommend',
    recCrop: 'Recommended Crop', conf: 'Confidence', aiExp: 'AI Explanation',
    searchCrops: 'Search Past Crops', cropNF: 'Crop not found', cropReady: 'Crop recommendation ready!',
    // Disease
    uploadLeaf: 'Upload Leaf Image', uploadSub: 'JPG, PNG up to 10MB',
    dropImg: 'Drop your leaf image here or', browse: 'browse',
    imgHint: 'Best results with close-up, well-lit images',
    detect: 'Detect Disease', detecting: 'Analyzing…',
    noAnalysis: 'No analysis yet', uploadFirst: 'Upload a leaf image to get started',
    detectedDisease: 'Detected Disease', fertSugg: 'Fertilizer Suggestion',
    pestSugg: 'Pesticide Suggestion', analysisOk: 'Disease analysis complete!',
    pleaseUpload: 'Please upload a leaf image', clear: 'Clear',
    // AI
    diseaseAdv: 'Disease Advisory', cropAdv: 'Crop Advisory',
    diseaseName: 'Disease Name', cropName: 'Crop Name',
    getAdv: 'Get AI Advisory', generating: 'Generating…',
    advReady: 'Advisory generated!', readyQ: 'Ready for your query',
    enterDetails: 'Enter disease or crop details to get advisory',
    fertRec: 'Fertilizer Recommendation', pestRec: 'Pesticide Recommendation',
    expLabel: 'Explanation', aiResult: 'AI Advisory Result',
    // Weather
    searchWeather: 'Search City Weather', enterCity: 'Enter city name…',
    cityNF: 'City not found or API error', enterCityErr: 'Enter a city name',
    humLbl: 'Humidity', windLbl: 'Wind Speed', pressLbl: 'Pressure',
    // Profile
    createProfile: 'Create Profile', editProfile: 'Edit Profile',
    fullname: 'Full Name', contact: 'Contact Number', address: 'Address',
    village: 'Village', district: 'District', state: 'State',
    pincode: 'Pincode', farmLoc: 'Farm Location',
    saveProfile: 'Save Profile', saving: 'Saving…',
    profileSaved: 'Profile saved!', profileDel: 'Profile deleted',
    delProfile: 'Delete Profile', confirmDel: 'Delete your profile?',
    cancel: 'Cancel', edit: 'Edit', del: 'Delete',
    // Email
    composeEmail: 'Compose Email', subject: 'Subject', message: 'Message',
    sendEmail: 'Send Email', sending: 'Sending…', emailSent: 'Email sent successfully!',
    quickAct: 'Quick Actions', welcomeEmail: 'Welcome Email',
    welcomeDesc: 'Send onboarding email', pestAlert: 'Pest Alert',
    pestDesc: 'Notify about pest detection', rainAlert: 'Rainfall Alert',
    rainDesc: 'Weather advisory', fillEmail: 'Fill all fields',
    // Admin
    regFarmers: 'Registered Farmers', totalF: 'total farmers',
    refresh: 'Refresh', noFarmers: 'No farmers yet', noFarmersSub: 'Registered farmers will appear here',
    nameLbl: 'Name', locLbl: 'Location', actionsLbl: 'Actions',
    viewLbl: 'View', confirmDelF: "Delete this farmer's profile?", farmerDel: 'Farmer deleted',
  },
  hi: {
    appName: 'AgriSmart', appSub: 'किसानों के लिए AI',
    dashboard: 'डैशबोर्ड', crop: 'फसल सुझाव', disease: 'रोग पहचान',
    ai: 'AI सलाह', weather: 'मौसम', profile: 'मेरी प्रोफ़ाइल',
    email: 'ईमेल अलर्ट', admin: 'किसान प्रबंधन', signout: 'साइन आउट',
    mainSection: 'मुख्य', adminSection: 'एडमिन',
    darkMode: 'डार्क', lightMode: 'लाइट',
    signin: 'साइन इन', signup: 'खाता बनाएं',
    username: 'उपयोगकर्ता नाम', password: 'पासवर्ड', emailLbl: 'ईमेल', role: 'भूमिका',
    farmerRole: 'किसान', adminRole: 'एडमिन',
    noAccount: 'खाता नहीं है?', haveAccount: 'पहले से खाता है?',
    register: 'पंजीकरण करें', signingIn: 'साइन इन हो रहा है…', creating: 'बन रहा है…',
    fillFields: 'सभी फ़ील्ड भरें', invalidCreds: 'गलत जानकारी',
    regSuccess: 'खाता बन गया! साइन इन करें।',
    goodDay: 'नमस्ते', dashSub: 'आपका स्मार्ट कृषि सहायक तैयार है।',
    quickTips: 'त्वरित सुझाव', howWorks: 'यह कैसे काम करता है',
    tip1: 'सबसे अच्छी रोग पहचान के लिए स्पष्ट पत्ती की तस्वीर अपलोड करें।',
    tip2: 'बेहतर फसल सुझाव के लिए सही NPK मान दर्ज करें।',
    tip3: 'खाद डालने से पहले मौसम जांचें — बारिश के दिन से बचें।',
    s1t: 'मिट्टी का डेटा', s1d: 'NPK, नमी, तापमान के मान दें',
    s2t: 'ML भविष्यवाणी', s2d: 'हमारा मॉडल सबसे अच्छी फसल सुझाता है',
    s3t: 'AI स्पष्टीकरण', s3d: 'उर्वरक और कीटनाशक की सलाह पाएं',
    clickOpen: 'खोलने के लिए क्लिक करें →',
    soilParams: 'मिट्टी के मापदंड', soilSub: 'मिट्टी और पर्यावरण डेटा दर्ज करें',
    temperature: 'तापमान (°C)', humidity: 'आर्द्रता (%)', rainfall: 'वर्षा (mm)',
    ph: 'मिट्टी pH (0–14)', nitrogen: 'नाइट्रोजन (N)', phosphorus: 'फास्फोरस (P)',
    potassium: 'पोटेशियम (K)', location: 'स्थान (वैकल्पिक)',
    getCrop: 'फसल सुझाव पाएं', analyzing: 'विश्लेषण हो रहा है…',
    noPred: 'अभी कोई भविष्यवाणी नहीं', fillSoil: 'मिट्टी के मापदंड भरें',
    recCrop: 'सुझावित फसल', conf: 'विश्वास', aiExp: 'AI स्पष्टीकरण',
    searchCrops: 'पिछली फसलें खोजें', cropNF: 'फसल नहीं मिली', cropReady: 'फसल सुझाव तैयार!',
    uploadLeaf: 'पत्ती की छवि अपलोड करें', uploadSub: 'JPG, PNG 10MB तक',
    dropImg: 'यहां पत्ती की छवि डालें या', browse: 'ब्राउज़ करें',
    imgHint: 'नजदीकी, अच्छी रोशनी वाली तस्वीर से सबसे अच्छे परिणाम',
    detect: 'रोग पहचानें', detecting: 'विश्लेषण हो रहा है…',
    noAnalysis: 'अभी कोई विश्लेषण नहीं', uploadFirst: 'पत्ती की छवि अपलोड करें',
    detectedDisease: 'पहचाना गया रोग', fertSugg: 'उर्वरक सुझाव',
    pestSugg: 'कीटनाशक सुझाव', analysisOk: 'रोग विश्लेषण पूर्ण!',
    pleaseUpload: 'कृपया पत्ती की छवि अपलोड करें', clear: 'हटाएं',
    diseaseAdv: 'रोग सलाह', cropAdv: 'फसल सलाह',
    diseaseName: 'रोग का नाम', cropName: 'फसल का नाम',
    getAdv: 'AI सलाह पाएं', generating: 'बन रहा है…',
    advReady: 'सलाह तैयार!', readyQ: 'आपके प्रश्न के लिए तैयार',
    enterDetails: 'रोग या फसल का विवरण दर्ज करें',
    fertRec: 'उर्वरक सिफारिश', pestRec: 'कीटनाशक सिफारिश',
    expLabel: 'स्पष्टीकरण', aiResult: 'AI सलाह परिणाम',
    searchWeather: 'शहर का मौसम खोजें', enterCity: 'शहर का नाम दर्ज करें…',
    cityNF: 'शहर नहीं मिला', enterCityErr: 'शहर का नाम दर्ज करें',
    humLbl: 'आर्द्रता', windLbl: 'हवा की गति', pressLbl: 'वायुदाब',
    createProfile: 'प्रोफ़ाइल बनाएं', editProfile: 'प्रोफ़ाइल संपादित करें',
    fullname: 'पूरा नाम', contact: 'संपर्क नंबर', address: 'पता',
    village: 'गांव', district: 'जिला', state: 'राज्य',
    pincode: 'पिनकोड', farmLoc: 'खेत का स्थान',
    saveProfile: 'प्रोफ़ाइल सहेजें', saving: 'सहेज रहा है…',
    profileSaved: 'प्रोफ़ाइल सहेजी गई!', profileDel: 'प्रोफ़ाइल हटाई गई',
    delProfile: 'प्रोफ़ाइल हटाएं', confirmDel: 'आपकी प्रोफ़ाइल हटाएं?',
    cancel: 'रद्द करें', edit: 'संपादित करें', del: 'हटाएं',
    composeEmail: 'ईमेल लिखें', subject: 'विषय', message: 'संदेश',
    sendEmail: 'ईमेल भेजें', sending: 'भेज रहा है…', emailSent: 'ईमेल सफलतापूर्वक भेजी!',
    quickAct: 'त्वरित क्रियाएं', welcomeEmail: 'स्वागत ईमेल',
    welcomeDesc: 'ऑनबोर्डिंग ईमेल भेजें', pestAlert: 'कीट अलर्ट',
    pestDesc: 'कीट पहचान की सूचना', rainAlert: 'वर्षा अलर्ट',
    rainDesc: 'मौसम सलाह', fillEmail: 'सभी फ़ील्ड भरें',
    regFarmers: 'पंजीकृत किसान', totalF: 'कुल किसान',
    refresh: 'ताज़ा करें', noFarmers: 'अभी कोई किसान नहीं', noFarmersSub: 'पंजीकृत किसान यहां दिखेंगे',
    nameLbl: 'नाम', locLbl: 'स्थान', actionsLbl: 'क्रियाएं',
    viewLbl: 'देखें', confirmDelF: 'इस किसान की प्रोफ़ाइल हटाएं?', farmerDel: 'किसान हटाया गया',
  },
};

export const getT = (lang) => translations[lang] || translations.en;
